extends GutTest
## Guards the committed menu theme against drifting away from the Design tokens.
##
## resources/themes/menu_theme.tres is generated by
## sources/ui/menu_theme_generator.gd. Nothing forces a contributor who edits a
## token to regenerate it, so these tests compare the committed resource with a
## freshly built one and fail when they disagree.

var theme: Theme


func before_each() -> void:
	theme = load(MenuTheme.THEME_PATH)


func test_committed_theme_matches_the_generator() -> void:
	# If this fails, regenerate the resource:
	#   godot --headless --path . --script sources/ui/menu_theme_generator.gd
	var expected: Theme = MenuTheme.build()

	for variation: String in expected.get_type_variation_list("Label"):
		assert_eq(theme.get_font_size("font_size", variation),
			expected.get_font_size("font_size", variation),
			"font size of Label variation %s is stale" % variation)
		assert_eq(theme.get_color("font_color", variation),
			expected.get_color("font_color", variation),
			"font colour of Label variation %s is stale" % variation)

	for variation: String in expected.get_type_variation_list("Button"):
		var committed: StyleBox = theme.get_stylebox("normal", variation)
		var built: StyleBox = expected.get_stylebox("normal", variation)
		assert_eq(committed.get_class(), built.get_class(),
			"style box type of Button variation %s is stale" % variation)
		if committed is StyleBoxFlat and built is StyleBoxFlat:
			assert_eq((committed as StyleBoxFlat).bg_color, (built as StyleBoxFlat).bg_color,
				"background colour of Button variation %s is stale" % variation)


func test_every_variation_is_registered() -> void:
	var labels: PackedStringArray = theme.get_type_variation_list("Label")
	for variation: StringName in [MenuTheme.VARIATION_TITLE, MenuTheme.VARIATION_HEADING,
			MenuTheme.VARIATION_CAPTION, MenuTheme.VARIATION_FIELD_LABEL,
			MenuTheme.VARIATION_ERROR, MenuTheme.VARIATION_CARD_TITLE,
			MenuTheme.VARIATION_CARD_HEADING, MenuTheme.VARIATION_CARD_BODY]:
		assert_has(labels, String(variation), "Label variation %s should be registered" % variation)

	var buttons: PackedStringArray = theme.get_type_variation_list("Button")
	for variation: StringName in [MenuTheme.VARIATION_PRIMARY_BUTTON,
			MenuTheme.VARIATION_SECONDARY_BUTTON, MenuTheme.VARIATION_CARD_SECONDARY_BUTTON,
			MenuTheme.VARIATION_INLINE_BUTTON, MenuTheme.VARIATION_TAB_PILL]:
		assert_has(buttons, String(variation), "Button variation %s should be registered" % variation)

	assert_has(theme.get_type_variation_list("PanelContainer"), String(MenuTheme.VARIATION_CARD),
		"the card panel variation should be registered")


func test_a_text_field_is_exactly_the_designed_height() -> void:
	# The field height comes from the style box padding rather than from a
	# custom_minimum_size set in each scene, so it is worth pinning down.
	var field: LineEdit = LineEdit.new()
	field.theme = theme
	add_child_autofree(field)

	assert_almost_eq(field.get_combined_minimum_size().y, float(Design.FIELD_HEIGHT), 1.0,
		"a themed LineEdit should be Design.FIELD_HEIGHT tall")


func test_a_tab_pill_is_exactly_the_designed_height() -> void:
	var pill: Button = Button.new()
	pill.theme = theme
	pill.theme_type_variation = MenuTheme.VARIATION_TAB_PILL
	pill.text = "Device 1"
	add_child_autofree(pill)

	assert_almost_eq(pill.get_combined_minimum_size().y, float(Design.PILL_HEIGHT), 1.0,
		"a themed tab pill should be Design.PILL_HEIGHT tall")


func test_disabled_primary_button_is_grey_not_purple() -> void:
	# The mockups grey a "Next" button out rather than dimming the purple, and
	# it is easy to lose that when regenerating.
	var disabled: StyleBox = theme.get_stylebox("disabled", MenuTheme.VARIATION_PRIMARY_BUTTON)
	assert_true(disabled is StyleBoxFlat, "the disabled primary button should be a flat box")
	assert_eq((disabled as StyleBoxFlat).bg_color, Design.GREY_LIGHT,
		"a disabled primary button should be grey")


func test_secondary_buttons_are_outlines_over_a_transparent_centre() -> void:
	for variation: StringName in [MenuTheme.VARIATION_SECONDARY_BUTTON,
			MenuTheme.VARIATION_CARD_SECONDARY_BUTTON]:
		var box: StyleBox = theme.get_stylebox("normal", variation)
		assert_true(box is StyleBoxFlat, "%s should be a flat box" % variation)
		var flat: StyleBoxFlat = box as StyleBoxFlat
		assert_eq(flat.bg_color.a, 0.0, "%s should not paint a background" % variation)
		assert_eq(flat.border_width_top, Design.BUTTON_BORDER,
			"%s should use the designed border width" % variation)
